In [2]:
import glob, re, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
%run cardiac_ml_tools.py

### var

In [4]:
dir_list = ["data_hearts_dd_0p2",
            "data_hearts_dd_0p2_geo_act_1_bcl",
            "data_hearts_dd_0p2_geo_act_1_bcl_gkr",
            "data_hearts_dd_0p2_geo_act_1_bcl_gkr_I",
            "data_hearts_dd_0p2_geo_act_2_bcl",
            "data_hearts_dd_0p2_geo_act_2_bcl_gkr",
            "data_hearts_dd_0p2_geo_act_2_bcl_gkr_I",
            "data_hearts_dd_0p2_geo_act_3_bcl",
            "data_hearts_dd_0p2_geo_act_3_bcl_gkr",
            "data_hearts_dd_0p2_geo_act_3_bcl_gkr_I",
            "data_hearts_dd_0p2_geo_inn",
            "data_hearts_dd_0p2_geo_inn_act_1_bcl",
            "data_hearts_dd_0p2_geo_inn_act_1_bcl_I",
            "data_hearts_dd_0p2_geo_inn_act_2_bcl",
            "data_hearts_dd_0p2_geo_inn_act_2_bcl_I",
            "data_hearts_dd_0p2_geo_inn_act_3_bcl",
            "data_hearts_dd_0p2_geo_inn_act_3_bcl_I",
            ]

---

# check the value range

### data_Y_Task3

In [5]:
first_string_search = "VmData" #-93.086583844575 49.530741145564

min_best = np.inf
max_best = -np.inf

import os
for _, dir_name in enumerate(dir_list):
    #-----------------
    #list_file_name
    list_file_name = os.listdir("../intracardiac_dataset/{}".format(dir_name))
    #-----------------
    #processing
    for _, file_name in enumerate(list_file_name):
        #-----------------
        #first_string
        first_string = file_name.split("_")[0]
        #-----------------
        #check file & processing
        if first_string == first_string_search:
            #-----------------
            #load data
            ndarray_VmData_rawdata = np.load("../intracardiac_dataset/{0}/{1}".format(dir_name,file_name))
            #-----------------
            #min, max
            min = ndarray_VmData_rawdata.min()
            max = ndarray_VmData_rawdata.max()
            #-----------------
            #check
            if min<min_best:
                min_best = min
            if max_best<max:
                max_best = max

print(min_best, max_best)

-93.086583844575 49.530741145564


### data_Y_Task4

In [6]:
min_best = np.inf #0
max_best = -np.inf #185

import os
for _, dir_name in enumerate(dir_list):
    #-----------------
    #list_file_name
    list_file_name = os.listdir("../intracardiac_dataset/{}".format(dir_name))
    #-----------------
    #processing
    for _, file_name in enumerate(list_file_name):
        #-----------------
        #first_string
        first_string = file_name.split("_")[0]
        #-----------------
        #check file & processing
        if first_string == "VmData":
            #-----------------
            #load data
            ndarray_VmData_rawdata = np.load("../intracardiac_dataset/{0}/{1}".format(dir_name,file_name))
            #activation_time
            ndarray_VmData_activation_time = get_activation_time(Vm=ndarray_VmData_rawdata)
            #-----------------
            #min, max
            min = ndarray_VmData_activation_time.min()
            max = ndarray_VmData_activation_time.max()
            #-----------------
            #check
            if min<min_best:
                min_best = min
            if max_best<max:
                max_best = max

print(min_best, max_best)

0 185


---

# create data_Y_Task3

### make dir

In [ ]:
"""import os
for cnt, dir_name in enumerate(dir_list):
    os.makedirs("../VmData_Activation/{}".format(dir_name), exist_ok=True)"""

### make VmData_Activation

In [8]:
import os
for _, dir_name in enumerate(dir_list):
    #-----------------
    #list_file_name
    list_file_name = os.listdir("../intracardiac_dataset/{}".format(dir_name))
    #-----------------
    #processing
    for _, file_name in enumerate(list_file_name):
        #-----------------
        #first_string
        first_string = file_name.split("_")[0]
        #-----------------
        #check file & processing
        if first_string == "VmData":
            #-----------------
            #load data
            ndarray_VmData_rawdata = np.load("../intracardiac_dataset/{0}/{1}".format(dir_name,file_name))
            #activation_time
            ndarray_VmData_activation_time = get_activation_time(Vm=ndarray_VmData_rawdata)
            #calc /500 (std to train) : (0,500) ->(/185)-> (0,1)
            ndarray_VmData_activation_time = ndarray_VmData_activation_time/185
            #-----------------
            #file_name_write
            file_name_write = "_".join([str(elem) for elem in file_name.split("_")[1:]])
            #-----------------
            #save
            np.save("../data_Y_Task3/{0}".format(file_name_write), ndarray_VmData_activation_time)

### check

In [9]:
import pandas as pd
import numpy as np
#ndarray_VmData_Activation = np.load('../data_Y_Task3/hearts_dd_0p2_geo_act_1_bcl_bcl.600.pattern.0.volunteer.v1.npy')
ndarray_VmData_Activation = np.load('../data_Y_Task3/hearts_dd_0p2_volunteer.v1_pattern.0.npy')
print(ndarray_VmData_Activation.shape)
print(ndarray_VmData_Activation)

(75, 1)
[[0.07027027]
 [0.10810811]
 [0.08108108]
 [0.03243243]
 [0.04324324]
 [0.01621622]
 [0.05405405]
 [0.03243243]
 [0.01081081]
 [0.05405405]
 [0.02702703]
 [0.01081081]
 [0.05405405]
 [0.03243243]
 [0.01081081]
 [0.02162162]
 [0.02162162]
 [0.04324324]
 [0.04864865]
 [0.02702703]
 [0.01081081]
 [0.04864865]
 [0.03243243]
 [0.01081081]
 [0.05405405]
 [0.03243243]
 [0.01081081]
 [0.02702703]
 [0.06486486]
 [0.03243243]
 [0.07027027]
 [0.04324324]
 [0.01621622]
 [0.03243243]
 [0.07027027]
 [0.03243243]
 [0.07567568]
 [0.04864865]
 [0.01621622]
 [0.07027027]
 [0.04324324]
 [0.01621622]
 [0.07027027]
 [0.04324324]
 [0.01621622]
 [0.05945946]
 [0.03783784]
 [0.01081081]
 [0.08108108]
 [0.01621622]
 [0.05405405]
 [0.04864865]
 [0.02702703]
 [0.01081081]
 [0.04324324]
 [0.02702703]
 [0.01081081]
 [0.06486486]
 [0.03243243]
 [0.02702703]
 [0.02702703]
 [0.05405405]
 [0.01081081]
 [0.02702703]
 [0.05945946]
 [0.02702703]
 [0.04864865]
 [0.02702703]
 [0.01081081]
 [0.06486486]
 [0.03783784

---

# create data_X, data_Y_Task4

In [10]:
import shutil
import os
for _, dir_name in enumerate(dir_list):
    #-----------------
    #list_file_name
    list_file_name = os.listdir("../intracardiac_dataset/{}".format(dir_name))
    #-----------------
    #processingß
    for _, file_name in enumerate(list_file_name):
        #-----------------
        #first_string
        first_string = file_name.split("_")[0]
        #-----------------
        #path_before
        path_before = "../intracardiac_dataset/{0}/{1}".format(dir_name,file_name)
        #-----------------
        #check file & processing
        if first_string == "pECGData":
            #-----------------
            #load data
            ndarray_pECGData_rawdata = np.load("../intracardiac_dataset/{0}/{1}".format(dir_name,file_name))
            #-----------------
            #ndarray_pECGData_std & T
            ndarray_pECGData_std = get_standard_leads(pECGnumpy=ndarray_pECGData_rawdata).T
            #-----------------
            #file_name_write
            file_name_write = "_".join([str(elem) for elem in file_name.split("_")[1:]])
            #-----------------
            #save
            np.save("../data_X/{0}".format(file_name_write), ndarray_pECGData_std)
        elif first_string == "VmData":
            #-----------------
            #file_name_write
            file_name_write = "_".join([str(elem) for elem in file_name.split("_")[1:]])
            #-----------------
            #load data
            ndarray_VmData_rawdata = np.load(path_before)
            #T
            ndarray_VmData_rawdata = ndarray_VmData_rawdata.T
            #calc /100 (std to train) : (-100,50) ->(+100)-> (0,150) >(/150)-> (0,1)
            ndarray_VmData_rawdata = (ndarray_VmData_rawdata+100)/150
            #save
            np.save("../data_Y_Task4/{}".format(file_name_write), ndarray_VmData_rawdata)
        elif first_string == ".bash":
            pass
        else:
            print(first_string)
            raise ValueError("error!!!")

In [11]:
ndarray_VmData_Activation = np.load('../data_X/hearts_dd_0p2_volunteer.v1_pattern.0.npy')
print(ndarray_VmData_Activation.shape)
print(ndarray_VmData_Activation)

(12, 500)
[[ 6.88542450e-02  1.29309706e-01  2.04173088e-01 ...  5.51596882e-05
   5.42432132e-05  5.33491153e-05]
 [ 7.07487330e-02  1.27802256e-01  1.90196902e-01 ...  1.94104350e-05
   1.95033560e-05  1.95972410e-05]
 [ 1.89448800e-03 -1.50745000e-03 -1.39761860e-02 ... -3.57492532e-05
  -3.47398572e-05 -3.37518743e-05]
 ...
 [ 1.91848489e-02  3.11466255e-02  3.03232624e-02 ...  2.10809510e-04
   2.08378000e-04  2.05981372e-04]
 [ 2.34811489e-02  4.30648895e-02  6.51849664e-02 ...  1.26850691e-04
   1.25679804e-04  1.24523858e-04]
 [ 2.49093939e-02  4.75615415e-02  7.71127564e-02 ...  1.45161080e-04
   1.43917270e-04  1.42687442e-04]]


In [12]:
ndarray_VmData_Activation = np.load('../data_Y_Task4/hearts_dd_0p2_volunteer.v1_pattern.0.npy')
print(ndarray_VmData_Activation.shape)
print(ndarray_VmData_Activation)

(75, 500)
[[0.10899189 0.10517984 0.10187717 ... 0.09407054 0.094057   0.09404359]
 [0.10899189 0.10517984 0.10187717 ... 0.09415868 0.09414425 0.09412998]
 [0.10899189 0.10517985 0.10187717 ... 0.09410618 0.09409228 0.09407851]
 ...
 [0.10899171 0.10517937 0.1018764  ... 0.09424316 0.09422812 0.09421323]
 [0.10899023 0.10517668 0.10187271 ... 0.09424536 0.09423082 0.09421642]
 [0.10907902 0.10701919 0.11647557 ... 0.0941266  0.09411272 0.09409898]]


---

### check # of data

In [13]:
import os

#-----------------
#list_file_name
list_file_name = os.listdir("../data_X")
print(len(list_file_name))

#-----------------
#list_file_name
list_file_name = os.listdir("../data_Y_Task3")
print(len(list_file_name))


#-----------------
#list_file_name
list_file_name = os.listdir("../data_Y_Task4")
print(len(list_file_name))

16117
16117
16117
